package com.example.luyan.smartmenu_shop.GreenDao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.luyan.smartmenu_process.MetaData.ORDERITEM;

import com.example.luyan.smartmenu_shop.GreenDao.ORDERITEMDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig oRDERITEMDaoConfig;

    private final ORDERITEMDao oRDERITEMDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        oRDERITEMDaoConfig = daoConfigMap.get(ORDERITEMDao.class).clone();
        oRDERITEMDaoConfig.initIdentityScope(type);

        oRDERITEMDao = new ORDERITEMDao(oRDERITEMDaoConfig, this);

        registerDao(ORDERITEM.class, oRDERITEMDao);
    }
    
    public void clear() {
        oRDERITEMDaoConfig.clearIdentityScope();
    }

    public ORDERITEMDao getORDERITEMDao() {
        return oRDERITEMDao;
    }

}
